version: "2"
services: 
  api:
    command: sh -c "
      python manage.py makemigrations 
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - mysql
    build: .
    ports:
      - "8096:8000"
    volumes:
      - ./api:/var/api
    env_file: 
      - .env
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
