# Generated by Django 4.2.4 on 2023-08-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalleteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pallete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('max_weight', models.FloatField()),
                ('status', models.CharField(choices=[('created', 'created'), ('in_process', 'in progress'), ('finished', 'finished')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.palletetype')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('z', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rotate', models.BooleanField()),
                ('need_edge_l', models.BooleanField()),
                ('complete_edge_l', models.BooleanField()),
                ('need_edge_t', models.BooleanField()),
                ('complete_edge_t', models.BooleanField()),
                ('need_edge_r', models.BooleanField()),
                ('complete_edge_r', models.BooleanField()),
                ('need_edge_b', models.BooleanField()),
                ('complete_edge_b', models.BooleanField()),
                ('xnc_need', models.BooleanField()),
                ('pallete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.pallete')),
            ],
        ),
    ]
