# Generated by Django 4.2.4 on 2023-08-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_alter_item_x_alter_item_y_alter_item_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
    ]
