# Generated by Django 4.2.4 on 2023-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_alter_item_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='from_temp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
